name: Update USD Rate

on:
  schedule:
    - cron: "*/10 * * * *"  # Her 10 dakikada bir çalışacak

jobs:
  update-rate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      
      - name: Print current directory
        run: pwd  # Çalışma dizinini göreceğiz

      - name: Run the script
        run: |
          python usd_fiyati.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add usd_fiyati.json
          git commit -m "Update USD rate"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
